name: Convert Website to APK
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Web App to APK
        uses: marb99/website2apk@v1
        with:
          app-name: "Zia Kitchen App"
          app-version: "1.0.0"
          package-name: "com.wonder0999.ziakitchen"
          website-url: "https://github.io"

      - name: Upload Finished App
        uses: actions/upload-artifact@v4
        with:
          name: Mobile-APK-Package
          path: ./*.apk
